language: node_js
sudo: false
node_js:
- stable
before_script:
- npm install karma-coveralls
cache:
  directories:
  - node_modules
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#annotator
    on_success: change
    on_failure: change
env:
  global:
  - secure: icwC3zPWB+IxS4xkDMxwuBw95oLmnsp8J1l78TXyVXpQTQKgUC7wIK/StcoT12qx06lcPnys5pJdsOP90Zk0otsBmNUcryirSKKBgovr03hhaECjnvxY9wXiSVozqT6/ScgjLi7j5IMGnNP8szXa+1IYsrSd7eUi06W+2qWHbDE=
